apiVersion: v1
kind: Service
metadata:
  name: {{ include "iam-account.fullname" . }}
  labels:
    {{- include "iam-account.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    {{- if and .Values.service.grpcPort (gt (int .Values.service.grpcPort) 0) }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    {{- end }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "iam-account.selectorLabels" . | nindent 4 }}
