// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/authn/supportTypes": {
            "get": {
                "description": "返回当前服务内置支持的认证方式（password / sms / oauth2 等）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authn"
                ],
                "summary": "支持的认证方式列表",
                "responses": {
                    "200": {
                        "description": "包含 types 数组，每项含 code / name / description",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/authz/supportTypes": {
            "get": {
                "description": "返回当前服务内置支持的授权方式（rbac / abac / acl / rebac 等）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authz"
                ],
                "summary": "支持的授权方式列表",
                "responses": {
                    "200": {
                        "description": "包含 types 数组，每项含 code / name / description",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8000",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "iam-hello API",
	Description:      "iam-hello 服务接口文档（脚手架示例）。\n仅在 config 中 enable_swagger=true 时暴露 /swagger/*any。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
